kind: pipeline
type: exec
name: deploy
platform:
  os: linux
  arch: amd64

steps:
  - name: pre-commit check
    commands:
      - cd /commit
      - cd pre-commit-terraform
      - git pull
      - docker build -t pre-commit .
      - cd /infrastructure-fivem && git pull --all
      - docker run -v $(pwd):/lint -w /lint pre-commit run -a

  - name: traefik
    commands:
      - cd /infrastructure-fivem
      - git pull --all
      - cd support/traefik/remote
      - docker-compose down
      - docker-compose up --build -d
    environment:
      CF_API_KEY:
        from_secret: CLOUDFLARE_API_KEY
      CF_API_EMAIL:
        from_secret: CLOUDFLARE_API_EMAIL
      DOMAIN_NAME:
        from_secret: CLOUDFLARE_DOMAIN_NAME

  - name: docker-compose test deploy
    commands:
      - cd /infrastructure-fivem
      - git pull --all
      - cd server
      - docker-compose down
      - docker-compose up --build -d
    environment:
      SERVER_KEY:
        from_secret: SERVER_KEY
      SVR_ADR:
        from_secret: SVR_ADR

  - name: blast-radius terraform
    commands:
      - cd /infrastructure-fivem
      - git pull --all
      - cd terraform
      - docker stop blast_radius || true
      - docker rm blast_radius || true
      - docker pull 28mm/blast-radius
      - docker run --detach -p 5000:5000 -v $(pwd):/data:ro  --name blast_radius --security-opt apparmor:unconfined --cap-add=SYS_ADMIN 28mm/blast-radius --serve .
