kind: pipeline
type: exec
name: deploy
platform:
  os: linux
  arch: amd64

steps:
  - name: pre-commit check
    commands:
      - cd /commit
      - cd pre-commit-terraform
      - git pull
      - docker build -t pre-commit .
      - docker run -v $(pwd):/lint -w /lint pre-commit run -a

  - name: docker-compose test deploy
    commands:
      - git clone https://github.com/gruberdev/infrastructure-fivem.git && cd infrastructure-fivem
      - git pull --all
      - docker-compose down
      - docker-compose up --build -d
    environment:
      SERVER_KEY:
        from_secret: SERVER_KEY
      SVR_ADR:
        from_secret: SVR_ADR
