kind: pipeline
name: default

steps:
  - name: test
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - sleep 10
      - apk update
      - curl -L --fail https://github.com/docker/compose/releases/download/1.28.6/run.sh -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
      - git clone https://github.com/gruberdev/infrastructure-fivem.git
      - git checkout drone-trigger-test
      - docker-compose down
      - docker-compose up --build -d

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersockad
    temp: {}
