kind: pipeline
type: exec
name: deploy
platform:
  os: linux
  arch: amd64

steps:
  - name: terraform deploy
    commands:
      - cd /root/terraform/infrastructure-fivem/terraform
      - echo "$SSHKEY" >> /root/terraform/infrastructure-fivem/terraform/resources/sshkey.pub
      - terraform init -upgrade
      - terraform destroy -auto-approve || true
      - git pull --all
      - terraform apply -auto-approve
    environment:
      SSHKEY:
        from_secret: sshkey
      TF_VAR_zone_id:
        from_secret: cloudflare_zone_id
      TF_VAR_cloudflare_email:
        from_secret: cloudflare_email
      TF_VAR_cloudflare_api_key:
        from_secret: cloudflare_api_key
      TF_VAR_vultr_token:
        from_secret: vultr_api_token
      TF_VAR_plan:
        from_secret: vultr_plan
      TF_VAR_label:
        from_secret: vultr_label
      TF_VAR_region:
        from_secret: vultr_region
      TF_VAR_hostname:
        from_secret: vultr_hostname
      TF_VAR_domain_type:
        from_secret: cf_domain_type
      TF_VAR_ttl:
        from_secret: cloudflare_ttl
      TF_VAR_tailscale_local:
        from_secret: tailscale_ip
      TF_VAR_tailscale_token:
        from_secret: tailscale_token
trigger:
  branch:
    - master
    - main
