version: "3.9"
services:
  fivem:
    depends_on:
      - mariadb
    build:
      context: ./
    env_file:
      - ./.env
    volumes:
      - fivem_data:/serverdata/serverfiles
    ports:
      - "30110:30110"
      - "30120:30120"
      - "30110:30110/udp"
      - "30120:30120/udp"
      - "40120:40120"
    environment:
      - GID=100
      - UID=99
      - GAME_CONFIG=server.cfg
    networks:
      - fivem
  mariadb:
    image: mariadb
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: 7phHqNnTFWoKkmUanqfk7i485CUmpdhQ
    networks:
      - fivem
volumes:
  fivem_data:
networks:
  fivem:
