version: "3"
services:
  fivem:
    image: ich777/fivemserver
    volumes:
      - /mnt/user/appdata/fivem:/serverdata/serverfiles
    ports:
      - "30110:30110"
      - "30120:30120"
      - "30110:30110/udp"
      - "30120:30120/udp"
    environment:
      - GET_HOSTS_FROM=dns
      - GID=100
      - UID=99
      - SRV_ADR=${SVR_ADR}
      - SERVER_KEY=${SERVER_KEY}
      - GAME_CONFIG=server.cfg
    labels:
      kompose.service.type: LoadBalancer
