version: "3.8"
services:
  fivem:
    build:
      context: ./
    env_file:
      - ./.env
    volumes:
      - fivem_data:/serverdata/serverfiles
    ports:
      - "30110:30110"
      - "30120:30120"
      - "30110:30110/udp"
      - "30120:30120/udp"
    environment:
      - GID=100
      - UID=99
      - GAME_CONFIG=server.cfg
volumes:
  fivem_data:
