version: "3.7"

services:
  mysql-master:
    image: "docker.io/bitnami/mysql:8.0-debian-10"
    env_file:
      - ./.env
    ports:
      - "3306"
    volumes:
      - "mysql_master_data:/bitnami/mysql/data"
    labels:
      - traefik.enable=false
    networks:
      - default
    environment:
      - MYSQL_REPLICATION_MODE=${MYSQL_REPLICATTION_MODE}
      - MYSQL_REPLICATION_USER=${MYSQL_REPLICATION_USER}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mysql/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6

  mysql-slave:
    image: "docker.io/bitnami/mysql:8.0-debian-10"
    ports:
      - "3306"
    networks:
      - default
    labels:
      - traefik.enable=false
    depends_on:
      - mysql-master
    environment:
      - MYSQL_REPLICATION_MODE={$MYSQL_REPLICATION_MODE}
      - MYSQL_REPLICATION_USER=${MYSQL_REPLICATION_USER}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_MASTER_HOST=${MYSQL_MASTER_HOST}
      - MYSQL_MASTER_PORT_NUMBER=${MYSQL_MASTER_PORT_NUMBER}
      - MYSQL_MASTER_ROOT_PASSWORD=${MYSQL_MASTER_ROOT_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mysql/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6

  fivem:
    env_file:
      - ./.env
    build:
      context: ./
    hostname: ${DOMAIN_NAME}
    depends_on:
      - mysql-slave
      - mysql-master
    labels:
      - traefik.http.routers.${SERVICE_NAME_1}.tls.certresolver=letsencrypt
      - traefik.http.routers.${SERVICE_NAME_1}.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.${SERVICE_NAME_1}.entrypoints=https
      - traefik.http.routers.${SERVICE_NAME_1}.tls=true
      - traefik.http.middlewares.serviceheaders.headers.accesscontrolalloworiginlist=*
      - traefik.http.routers.service.middlewares=viewsheaders
      - traefik.port=30110
      - traefik.port=30110/udp
      - traefik.port=30120
      - traefik.port=30120/udp
      - traefik.port=80
      - traefik.port=443
    networks:
      - traefik_public
      - default
    restart: unless-stopped

volumes:
  mysql_master_data:
    driver: local

networks:
  traefik_public:
    external: true
  default:
    external:
      name: fivem
