version: "3"
services:
  fivem:
    build:
      context: ./
    volumes:
      - /mnt/user/appdata/fivem:/serverdata/serverfiles
    networks:
      - caddy_public
    ports:
      - "30110:30110"
      - "30120:30120"
      - "30110:30110/udp"
      - "30120:30120/udp"
    environment:
      - GET_HOSTS_FROM=dns
      - GID=100
      - UID=99
      - SRV_ADR=${SVR_ADR}
      - SERVER_KEY=${SERVER_KEY}
      - GAME_CONFIG=server.cfg

networks:
  caddy_public:
    external: true
