name: Publish Docker image to GitHub Package Registry
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      - name: Publish container image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: basic-fivem-server
          registry: ghcr.io
          tags: latest
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
